from open_data_app.models.college import College
from open_data_app.models.carnegie import Carnegie
from open_data_app.models.degree import Degree
from open_data_app.models.level import Level
from open_data_app.models.locale import Locale
from open_data_app.models.ownership import Ownership
from open_data_app.models.region import Region
from open_data_app.models.religion import Religion
from open_data_app.models.state import State
from open_data_app.models.dictionary import Dictionary
