from .college import College
from .carnegie import Carnegie
from .degree import Degree
from .level import Level
from .locale import Locale
from .ownership import Ownership
from .region import Region
from .religion import Religion
from .state import State
