# Generated by Django 2.1.2 on 2018-10-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carnegie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_num', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('zip', models.CharField(blank=True, max_length=255)),
                ('latitude', models.CharField(blank=True, max_length=255)),
                ('longitude', models.CharField(blank=True, max_length=255)),
                ('hist_black', models.IntegerField(null=True)),
                ('predom_black', models.IntegerField(null=True)),
                ('hispanic', models.IntegerField(null=True)),
                ('men_only', models.IntegerField(null=True)),
                ('women_only', models.IntegerField(null=True)),
                ('online_only', models.IntegerField(null=True)),
                ('cur_operating', models.IntegerField(null=True)),
                ('full_data', models.TextField()),
                ('carnegie_basic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Carnegie')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_num', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='highest_grad_degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Degree'),
        ),
        migrations.AddField(
            model_name='college',
            name='inst_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Level'),
        ),
        migrations.AddField(
            model_name='college',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Locale'),
        ),
        migrations.AddField(
            model_name='college',
            name='ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Ownership'),
        ),
        migrations.AddField(
            model_name='college',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Region'),
        ),
        migrations.AddField(
            model_name='college',
            name='religous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Religion'),
        ),
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_data_app.State'),
        ),
    ]
