# Generated by Django 2.1.2 on 2018-10-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.IntegerField()),
                ('zip', models.CharField(max_length=255)),
                ('region', models.IntegerField()),
                ('ownership', models.IntegerField()),
                ('locale', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('grad_degree', models.FloatField()),
                ('camegie_basic', models.IntegerField()),
                ('hist_black', models.IntegerField()),
                ('predom_black', models.IntegerField()),
                ('hispanic', models.IntegerField()),
                ('men_only', models.IntegerField()),
                ('women_only', models.IntegerField()),
                ('religous', models.IntegerField()),
                ('online_only', models.IntegerField()),
                ('operating', models.IntegerField()),
                ('inst_level', models.IntegerField()),
                ('faculty_salary', models.IntegerField()),
                ('cur_operating', models.IntegerField()),
                ('full_data', models.TextField()),
            ],
        ),
    ]
