# Generated by Django 2.1.2 on 2018-10-28 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='carnegie_basic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Carnegie'),
        ),
        migrations.AlterField(
            model_name='college',
            name='highest_grad_degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Degree'),
        ),
        migrations.AlterField(
            model_name='college',
            name='inst_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Level'),
        ),
        migrations.AlterField(
            model_name='college',
            name='ownership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Ownership'),
        ),
        migrations.AlterField(
            model_name='college',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Region'),
        ),
        migrations.AlterField(
            model_name='college',
            name='religous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Religion'),
        ),
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='open_data_app.State'),
        ),
    ]
