# Generated by Django 2.1.2 on 2018-10-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='faculty_salary',
        ),
        migrations.RemoveField(
            model_name='college',
            name='grad_degree',
        ),
        migrations.RemoveField(
            model_name='college',
            name='operating',
        ),
        migrations.AddField(
            model_name='college',
            name='highest_grad_degree',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='camegie_basic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='cur_operating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='hispanic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='hist_black',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='inst_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='locale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='men_only',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='online_only',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='ownership',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='predom_black',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='region',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='religous',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='women_only',
            field=models.IntegerField(null=True),
        ),
    ]
