# Generated by Django 2.1.2 on 2018-10-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0002_auto_20181028_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Locale'),
        ),
    ]
