# Generated by Django 2.1.2 on 2018-10-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0002_auto_20181028_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='zip',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
