# Generated by Django 2.1.2 on 2018-10-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0003_auto_20181028_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
