# Generated by Django 2.1.2 on 2018-10-28 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0003_auto_20181028_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='latitude',
            field=models.CharField(blank=True, default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='longitude',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
