# Generated by Django 2.1.2 on 2019-12-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0004_page_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['name']},
        ),
    ]
