# Generated by Django 2.1.2 on 2019-12-25 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0005_auto_20191225_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={},
        ),
    ]
