# Generated by Django 2.1.2 on 2019-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0006_auto_20191225_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('items_quantity', models.IntegerField(blank=True)),
                ('is_top_selection', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='colleges',
        ),
        migrations.AddField(
            model_name='rating',
            name='filters',
            field=models.ManyToManyField(to='open_data_app.Filter'),
        ),
    ]
