# Generated by Django 2.1.2 on 2019-12-25 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0008_filter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='parameter',
        ),
        migrations.AddField(
            model_name='filter',
            name='carnegie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.Carnegie'),
        ),
        migrations.AddField(
            model_name='filter',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.Degree'),
        ),
        migrations.AddField(
            model_name='filter',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.Level'),
        ),
        migrations.AddField(
            model_name='filter',
            name='locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.Locale'),
        ),
        migrations.AddField(
            model_name='filter',
            name='ownership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.Ownership'),
        ),
        migrations.AddField(
            model_name='filter',
            name='parameter_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='parameter_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.Region'),
        ),
        migrations.AddField(
            model_name='filter',
            name='religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.Religion'),
        ),
        migrations.AddField(
            model_name='filter',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.State'),
        ),
    ]
