# Generated by Django 2.1.2 on 2018-11-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0008_auto_20181103_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='city'),
        ),
    ]
