# Generated by Django 2.1.2 on 2018-11-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0010_auto_20181103_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='college'),
        ),
    ]
