# Generated by Django 2.1.2 on 2019-12-25 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0011_auto_20191225_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='carnegie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.Carnegie'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.Degree'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.Level'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='locale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.Locale'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.Ownership'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.Region'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.Religion'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_data_app.State'),
        ),
    ]
