# Generated by Django 2.1.2 on 2019-12-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0012_auto_20191225_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='is_top_selection',
        ),
    ]
