# Generated by Django 2.1.2 on 2019-12-26 14:36

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0013_remove_filter_is_top_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
