# Generated by Django 2.1.2 on 2018-11-03 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0015_auto_20181103_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='carnegie_basic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Carnegie', verbose_name='carnegie'),
        ),
        migrations.AlterField(
            model_name='college',
            name='highest_grad_degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Degree', verbose_name='degree'),
        ),
        migrations.AlterField(
            model_name='college',
            name='inst_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Level', verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='college',
            name='locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Locale', verbose_name='locale'),
        ),
        migrations.AlterField(
            model_name='college',
            name='religous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='open_data_app.Religion', verbose_name='religion'),
        ),
        migrations.AlterField(
            model_name='college',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
