# Generated by Django 2.1.2 on 2018-11-04 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0016_auto_20181103_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='open_data_app.State', verbose_name='state'),
        ),
    ]
