# Generated by Django 2.1.2 on 2018-11-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0017_auto_20181104_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='hist_black',
            field=models.IntegerField(null=True, verbose_name='hist_black'),
        ),
    ]
