# Generated by Django 2.1.2 on 2018-11-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0019_auto_20181104_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='agriculture',
            field=models.IntegerField(null=True, verbose_name='agriculture'),
        ),
        migrations.AddField(
            model_name='college',
            name='architecture',
            field=models.IntegerField(null=True, verbose_name='architecture'),
        ),
        migrations.AddField(
            model_name='college',
            name='biological',
            field=models.IntegerField(null=True, verbose_name='biological'),
        ),
        migrations.AddField(
            model_name='college',
            name='business_marketing',
            field=models.IntegerField(null=True, verbose_name='business_marketing'),
        ),
        migrations.AddField(
            model_name='college',
            name='communication',
            field=models.IntegerField(null=True, verbose_name='communication'),
        ),
        migrations.AddField(
            model_name='college',
            name='communications_technology',
            field=models.IntegerField(null=True, verbose_name='communications_technology'),
        ),
        migrations.AddField(
            model_name='college',
            name='computer',
            field=models.IntegerField(null=True, verbose_name='computer'),
        ),
        migrations.AddField(
            model_name='college',
            name='construction',
            field=models.IntegerField(null=True, verbose_name='construction'),
        ),
        migrations.AddField(
            model_name='college',
            name='education',
            field=models.IntegerField(null=True, verbose_name='education'),
        ),
        migrations.AddField(
            model_name='college',
            name='engineering',
            field=models.IntegerField(null=True, verbose_name='engineering'),
        ),
        migrations.AddField(
            model_name='college',
            name='engineering_technology',
            field=models.IntegerField(null=True, verbose_name='engineering_technology'),
        ),
        migrations.AddField(
            model_name='college',
            name='english',
            field=models.IntegerField(null=True, verbose_name='english'),
        ),
        migrations.AddField(
            model_name='college',
            name='ethnic_cultural_gender',
            field=models.IntegerField(null=True, verbose_name='ethnic_cultural_gender'),
        ),
        migrations.AddField(
            model_name='college',
            name='family_consumer_science',
            field=models.IntegerField(null=True, verbose_name='family_consumer_science'),
        ),
        migrations.AddField(
            model_name='college',
            name='health',
            field=models.IntegerField(null=True, verbose_name='health'),
        ),
        migrations.AddField(
            model_name='college',
            name='history',
            field=models.IntegerField(null=True, verbose_name='history'),
        ),
        migrations.AddField(
            model_name='college',
            name='humanities',
            field=models.IntegerField(null=True, verbose_name='humanities'),
        ),
        migrations.AddField(
            model_name='college',
            name='language',
            field=models.IntegerField(null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='college',
            name='legal',
            field=models.IntegerField(null=True, verbose_name='legal'),
        ),
        migrations.AddField(
            model_name='college',
            name='library',
            field=models.IntegerField(null=True, verbose_name='library'),
        ),
        migrations.AddField(
            model_name='college',
            name='mathematics',
            field=models.IntegerField(null=True, verbose_name='mathematics'),
        ),
        migrations.AddField(
            model_name='college',
            name='mechanic_repair_technology',
            field=models.IntegerField(null=True, verbose_name='mechanic_repair_technology'),
        ),
        migrations.AddField(
            model_name='college',
            name='military',
            field=models.IntegerField(null=True, verbose_name='military'),
        ),
        migrations.AddField(
            model_name='college',
            name='multidiscipline',
            field=models.IntegerField(null=True, verbose_name='multidiscipline'),
        ),
        migrations.AddField(
            model_name='college',
            name='parks_recreation_fitness',
            field=models.IntegerField(null=True, verbose_name='parks_recreation_fitness'),
        ),
        migrations.AddField(
            model_name='college',
            name='personal_culinary',
            field=models.IntegerField(null=True, verbose_name='personal_culinary'),
        ),
        migrations.AddField(
            model_name='college',
            name='philosophy_religious',
            field=models.IntegerField(null=True, verbose_name='philosophy_religious'),
        ),
        migrations.AddField(
            model_name='college',
            name='physical_science',
            field=models.IntegerField(null=True, verbose_name='physical_science'),
        ),
        migrations.AddField(
            model_name='college',
            name='precision_production',
            field=models.IntegerField(null=True, verbose_name='precision_production'),
        ),
        migrations.AddField(
            model_name='college',
            name='psychology',
            field=models.IntegerField(null=True, verbose_name='psychology'),
        ),
        migrations.AddField(
            model_name='college',
            name='public_administration_social_service',
            field=models.IntegerField(null=True, verbose_name='public_administration_social_service'),
        ),
        migrations.AddField(
            model_name='college',
            name='resources',
            field=models.IntegerField(null=True, verbose_name='resources'),
        ),
        migrations.AddField(
            model_name='college',
            name='science_technology',
            field=models.IntegerField(null=True, verbose_name='science_technology'),
        ),
        migrations.AddField(
            model_name='college',
            name='security_law_enforcement',
            field=models.IntegerField(null=True, verbose_name='security_law_enforcement'),
        ),
        migrations.AddField(
            model_name='college',
            name='social_science',
            field=models.IntegerField(null=True, verbose_name='social_science'),
        ),
        migrations.AddField(
            model_name='college',
            name='theology_religious_vocation',
            field=models.IntegerField(null=True, verbose_name='theology_religious_vocation'),
        ),
        migrations.AddField(
            model_name='college',
            name='transportation',
            field=models.IntegerField(null=True, verbose_name='transportation'),
        ),
        migrations.AddField(
            model_name='college',
            name='visual_performing',
            field=models.IntegerField(null=True, verbose_name='visual_performing'),
        ),
    ]
