# Generated by Django 2.1.2 on 2018-11-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0021_auto_20181124_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='act_cumulative',
            field=models.FloatField(null=True, verbose_name='act_cumulative'),
        ),
        migrations.AddField(
            model_name='college',
            name='act_english',
            field=models.FloatField(null=True, verbose_name='act_english'),
        ),
        migrations.AddField(
            model_name='college',
            name='act_math',
            field=models.FloatField(null=True, verbose_name='act_math'),
        ),
        migrations.AddField(
            model_name='college',
            name='act_writing',
            field=models.FloatField(null=True, verbose_name='act_writing'),
        ),
        migrations.AddField(
            model_name='college',
            name='admission_rate',
            field=models.FloatField(null=True, verbose_name='admission_rate'),
        ),
        migrations.AddField(
            model_name='college',
            name='average_cost_of_attendance_academic',
            field=models.FloatField(null=True, verbose_name='average_cost_of_attendance_academic'),
        ),
        migrations.AddField(
            model_name='college',
            name='average_cost_of_attendance_program',
            field=models.FloatField(null=True, verbose_name='average_cost_of_attendance_program'),
        ),
        migrations.AddField(
            model_name='college',
            name='average_net_price_priv_110',
            field=models.FloatField(null=True, verbose_name='average_net_price_priv_110'),
        ),
        migrations.AddField(
            model_name='college',
            name='average_net_price_priv_30',
            field=models.FloatField(null=True, verbose_name='average_net_price_priv_30'),
        ),
        migrations.AddField(
            model_name='college',
            name='average_net_price_priv_48',
            field=models.FloatField(null=True, verbose_name='average_net_price_priv_48'),
        ),
        migrations.AddField(
            model_name='college',
            name='average_net_price_priv_75',
            field=models.FloatField(null=True, verbose_name='average_net_price_priv_75'),
        ),
        migrations.AddField(
            model_name='college',
            name='average_net_price_private',
            field=models.FloatField(null=True, verbose_name='average_net_price_private'),
        ),
        migrations.AddField(
            model_name='college',
            name='average_net_price_pub_110',
            field=models.FloatField(null=True, verbose_name='average_net_price_pub_110'),
        ),
        migrations.AddField(
            model_name='college',
            name='average_net_price_pub_30',
            field=models.FloatField(null=True, verbose_name='average_net_price_pub_30'),
        ),
        migrations.AddField(
            model_name='college',
            name='average_net_price_pub_48',
            field=models.FloatField(null=True, verbose_name='average_net_price_pub_48'),
        ),
        migrations.AddField(
            model_name='college',
            name='average_net_price_pub_75',
            field=models.FloatField(null=True, verbose_name='average_net_price_pub_75'),
        ),
        migrations.AddField(
            model_name='college',
            name='average_net_price_public',
            field=models.FloatField(null=True, verbose_name='average_net_price_public'),
        ),
        migrations.AddField(
            model_name='college',
            name='completion_rate_four_year',
            field=models.FloatField(null=True, verbose_name='completion_rate_four_year'),
        ),
        migrations.AddField(
            model_name='college',
            name='completion_rate_less_four_year',
            field=models.FloatField(null=True, verbose_name='completion_rate_less_four_year'),
        ),
        migrations.AddField(
            model_name='college',
            name='debt_completed',
            field=models.FloatField(null=True, verbose_name='debt_completed'),
        ),
        migrations.AddField(
            model_name='college',
            name='debt_not_completed',
            field=models.FloatField(null=True, verbose_name='debt_not_completed'),
        ),
        migrations.AddField(
            model_name='college',
            name='federal_loan',
            field=models.FloatField(null=True, verbose_name='federal_loan'),
        ),
        migrations.AddField(
            model_name='college',
            name='in_state_tuition',
            field=models.FloatField(null=True, verbose_name='in_state_tuition'),
        ),
        migrations.AddField(
            model_name='college',
            name='mean_earnings',
            field=models.FloatField(null=True, verbose_name='mean_earnings'),
        ),
        migrations.AddField(
            model_name='college',
            name='monthly_payments',
            field=models.FloatField(null=True, verbose_name='monthly_payments'),
        ),
        migrations.AddField(
            model_name='college',
            name='out_state_tuition',
            field=models.FloatField(null=True, verbose_name='out_state_tuition'),
        ),
        migrations.AddField(
            model_name='college',
            name='pell_grand',
            field=models.FloatField(null=True, verbose_name='pell_grand'),
        ),
        migrations.AddField(
            model_name='college',
            name='sat_average',
            field=models.FloatField(null=True, verbose_name='sat_average'),
        ),
        migrations.AddField(
            model_name='college',
            name='sat_math',
            field=models.FloatField(null=True, verbose_name='sat_math'),
        ),
        migrations.AddField(
            model_name='college',
            name='sat_reading',
            field=models.FloatField(null=True, verbose_name='sat_reading'),
        ),
        migrations.AddField(
            model_name='college',
            name='sat_writing',
            field=models.FloatField(null=True, verbose_name='sat_writing'),
        ),
        migrations.AddField(
            model_name='college',
            name='students_asian',
            field=models.FloatField(null=True, verbose_name='students_asian'),
        ),
        migrations.AddField(
            model_name='college',
            name='students_black',
            field=models.FloatField(null=True, verbose_name='students_black'),
        ),
        migrations.AddField(
            model_name='college',
            name='students_family_income',
            field=models.FloatField(null=True, verbose_name='students_family_income'),
        ),
        migrations.AddField(
            model_name='college',
            name='students_female',
            field=models.FloatField(null=True, verbose_name='students_female'),
        ),
        migrations.AddField(
            model_name='college',
            name='students_hispanic',
            field=models.FloatField(null=True, verbose_name='students_hispanic'),
        ),
        migrations.AddField(
            model_name='college',
            name='students_multiple_races',
            field=models.FloatField(null=True, verbose_name='students_multiple_races'),
        ),
        migrations.AddField(
            model_name='college',
            name='students_native',
            field=models.FloatField(null=True, verbose_name='students_native'),
        ),
        migrations.AddField(
            model_name='college',
            name='students_non_resident',
            field=models.FloatField(null=True, verbose_name='students_non_resident'),
        ),
        migrations.AddField(
            model_name='college',
            name='students_pacific',
            field=models.FloatField(null=True, verbose_name='students_pacific'),
        ),
        migrations.AddField(
            model_name='college',
            name='students_part_time',
            field=models.FloatField(null=True, verbose_name='students_part_time'),
        ),
        migrations.AddField(
            model_name='college',
            name='students_unknown_race',
            field=models.FloatField(null=True, verbose_name='students_unknown_race'),
        ),
        migrations.AddField(
            model_name='college',
            name='students_white',
            field=models.FloatField(null=True, verbose_name='students_white'),
        ),
        migrations.AddField(
            model_name='college',
            name='undergrad_students',
            field=models.FloatField(null=True, verbose_name='undergrad_students'),
        ),
    ]
