# Generated by Django 2.1.2 on 2018-11-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0022_auto_20181125_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='average_net_price_priv_110_plus',
            field=models.FloatField(null=True, verbose_name='average_net_price_priv_110_plus'),
        ),
        migrations.AddField(
            model_name='college',
            name='average_net_price_pub_110_plus',
            field=models.FloatField(null=True, verbose_name='average_net_price_pub_110_plus'),
        ),
    ]
