# Generated by Django 2.1.2 on 2018-12-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0023_auto_20181125_1731'),
    ]

    operations = [
    ]
