# Generated by Django 2.1.2 on 2019-01-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0024_auto_20181216_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='completion_rate_four_year_pooled',
            field=models.FloatField(null=True, verbose_name='completion_rate_four_year_pooled'),
        ),
        migrations.AddField(
            model_name='college',
            name='debt_completed_median',
            field=models.FloatField(null=True, verbose_name='debt_completed_median'),
        ),
        migrations.AddField(
            model_name='college',
            name='median_earnings',
            field=models.FloatField(null=True, verbose_name='median_earnings'),
        ),
    ]
