# Generated by Django 2.1.2 on 2019-01-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0025_auto_20190103_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='calc_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='completion_rate_less_four_year_pooled',
            field=models.FloatField(null=True, verbose_name='completion_rate_less_four_year_pooled'),
        ),
        migrations.AddField(
            model_name='college',
            name='retention_rate_four_year_pooled',
            field=models.FloatField(null=True, verbose_name='retention_rate_four_year_pooled'),
        ),
        migrations.AddField(
            model_name='college',
            name='retention_rate_less_four_year_pooled',
            field=models.FloatField(null=True, verbose_name='retention_rate_less_four_year_pooled'),
        ),
    ]
