# Generated by Django 2.1.2 on 2019-01-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0026_auto_20190104_1159'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['state'], name='open_data_a_state_i_38b92b_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['region'], name='open_data_a_region__2b8398_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['ownership'], name='open_data_a_ownersh_2caee3_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['locale'], name='open_data_a_locale__0ffb89_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['highest_grad_degree'], name='open_data_a_highest_85cdbc_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['carnegie_basic'], name='open_data_a_carnegi_68a6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['inst_level'], name='open_data_a_inst_le_b31bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['agriculture'], name='open_data_a_agricul_d24311_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['architecture'], name='open_data_a_archite_0d12c4_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['ethnic_cultural_gender'], name='open_data_a_ethnic__f222e1_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['business_marketing'], name='open_data_a_busines_1cc21a_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['communication'], name='open_data_a_communi_ee604e_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['communications_technology'], name='open_data_a_communi_5222ab_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['computer'], name='open_data_a_compute_5dc5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['construction'], name='open_data_a_constru_78abea_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['education'], name='open_data_a_educati_5d7be4_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['engineering'], name='open_data_a_enginee_95cb43_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['engineering_technology'], name='open_data_a_enginee_56912e_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['english'], name='open_data_a_english_edc45b_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['family_consumer_science'], name='open_data_a_family__6a5143_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['language'], name='open_data_a_languag_d41b26_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['health'], name='open_data_a_health_6baa87_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['history'], name='open_data_a_history_b78d04_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['security_law_enforcement'], name='open_data_a_securit_1c6d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['legal'], name='open_data_a_legal_26a325_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['humanities'], name='open_data_a_humanit_4dd90d_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['library'], name='open_data_a_library_ef258d_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['mathematics'], name='open_data_a_mathema_2e9e38_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['mechanic_repair_technology'], name='open_data_a_mechani_b1e0de_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['military'], name='open_data_a_militar_f36a49_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['multidiscipline'], name='open_data_a_multidi_f4baf9_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['resources'], name='open_data_a_resourc_fdd893_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['parks_recreation_fitness'], name='open_data_a_parks_r_cd756e_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['personal_culinary'], name='open_data_a_persona_3a3cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['philosophy_religious'], name='open_data_a_philoso_8bdeab_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['physical_science'], name='open_data_a_physica_4198cf_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['precision_production'], name='open_data_a_precisi_16ed98_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['psychology'], name='open_data_a_psychol_833dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['public_administration_social_service'], name='open_data_a_public__e7810c_idx'),
        ),
    ]
