# Generated by Django 2.1.2 on 2019-01-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0027_auto_20190117_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='full_data',
        ),
    ]
