# Generated by Django 2.1.2 on 2019-08-14 08:53

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0028_remove_college_full_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_slugs', jsonfield.fields.JSONField()),
                ('college_property_titles', jsonfield.fields.JSONField()),
            ],
        ),
    ]
