# Generated by Django 2.1.2 on 2019-08-14 09:06

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0029_dictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='college_property_titles',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='discipline_slugs',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
