# Generated by Django 2.1.2 on 2019-08-14 09:13

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_data_app', '0030_auto_20190814_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='college_property_titles',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='discipline_slugs',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='content',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
